### ISSUE TITLE
sensor manifest appears to use within inconsistently

### ISSUE THREAD

**Issue by phoddie** [dtex/j5e#72]
The sensor manifest includes the `withinable`module as `j5e/within`

https://github.com/dtex/j5e/blob/3390ab33e1b55b7c89ceed58a6bc616aa97fafca/lib/sensor/manifest.json#L5

Later it tries to preload the module as `j5e/withinable` which fails because the module specifier is `j5e/within`:

https://github.com/dtex/j5e/blob/3390ab33e1b55b7c89ceed58a6bc616aa97fafca/lib/sensor/manifest.json#L9-L10

Should line 5 use `j5e/withinable` instead?

**Comment by dtex** [comment]
Yes, thank you for the catch. I waffled on the name and missed this.
